# Generated by Django 3.2.16 on 2022-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221225_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to='./photos', verbose_name='Фото автора'),
        ),
    ]
